### ISSUE TITLE
Problem adding Youtube under Help to SMplayer

### ISSUE THREAD

**Issue by walkman1943** [smplayer-dev/smplayer#1062]
An error happened while downloading the file:
Error transferring https://youtube-dl.org/downloads/latest/youtube-dl.exe - server replied: Unavailable For Legal Reasons**

Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Your Enviroment**
 - SMPlayer version:
 - OS: [e.g. Windows 10]
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [ ] MPV

**Logs**
Reproduce the bug in your computer and attach the smplayer log (menu View) here.

**Additional context**

**Comment by smplayer-dev** [comment]
Fixed in version 24.5.0.10323
https://github.com/smplayer-dev/smplayer/releases/tag/v24.5.0.10323

**Comment by walkman1943** [comment]
Hi Ricardo

Thanks for the update but it still doesn't fix the Youtube end of things.

Have enclosed the log above which I hope may help with the problem.

When I go to help and try to install/update to Youtube it fails to appear

In the View column. Hope you can help with this please.

Kind regards

Gerald








Add your comments and collaborate with others in real time. You don't need
to download Acrobat or sign up to access the file.

**Comment by walkman1943** [comment]
Sorry but as I said Youtube is not working under most recent version I downloaded and ibstalled.

**Comment by smplayer-dev** [comment]
Try selecting "yt-dlp" instead of "youtube-dl" in preferences -> network.

**Comment by walkman1943** [comment]
Hi Ricardo

I did what you have suggested but Youtube still refuses to appear under View in SMPlayer.

Please help if you can.

Regards

Gerald

**Comment by smplayer-dev** [comment]
There isn't any Youtube option under View, it was removed. Just copy the Youtube URL and enter it in Open -> URL.

**Comment by walkman1943** [comment]
Hi Ricardo

Got it now but I’m not sure if it is of any benefit. You have to still open Youtube and find

what you want to watch and use the url as you say. But it means that you have to do

that for each program you watch on Youtube. Seems handier just to watch youtube itself unless

you can come up with a better way in SMPlayer which by the way is a fantastic program. Just

a thought at the moment. Keep up the good work.

Kind regards

Gerald
