### ISSUE TITLE
Wrong ascpect ratio when you rotate a video.

### ISSUE THREAD

**Issue by SafeReader** [smplayer-dev/smplayer#1226]
**Describe the bug**
This is happening to SMplayer to my computers desktop and laptop.
Ι did a clear install of SMplayer. All settings to default.
Wrong aspect ratio when you rotate a video.

**To Reproduce**
1. Do a clean install of SMplayer with default settings. It doesn't matter the skin.
2. Open any video mp4.
3. Click on Video on the top horizontal bar
4. Scroll down to 'Rotate: and choose a rotation.
5. I saw the aspect ratio is wrong because the picture of the video is distorted in one direction (stretched)

**Expected behavior**
I expected in rotation of video to keep the correct aspect ratio the video.
I downloaded the previous version 24.5 and works fine.

**Screenshots**

<img width="1919" height="1049" alt="Image" src="https://github.com/user-attachments/assets/1a2f0e8c-9b5d-4f51-9b76-2f3e6364d559" />
<img width="1916" height="1047" alt="Image" src="https://github.com/user-attachments/assets/969fde5e-6780-412f-a738-7e8dbf45c649" />
![Image](https://github.com/user-attachments/assets/e876ffc4-a73b-47b1-b10e-fb276f212b95)

**Your Enviroment**
 - SMPlayer version: Version: 25.6.0 (revision 10369) (64-bit)
 - OS: [Windows 11 Pro]
 - Multimedia engine you're using with SMPlayer (preferences -> general):
[X] MPV
**Logs**
[SMplayer Log.log](https://github.com/user-attachments/files/21470214/SMplayer.Log.log)
[mpv LOG.log](https://github.com/user-attachments/files/21470213/mpv.LOG.log)

**Comment by smplayer-dev** [comment]
Could you test the very latest version?
https://github.com/smplayer-dev/smplayer/releases/tag/v10388

**Comment by orastes** [comment]
> Could you test the very latest version? https://github.com/smplayer-dev/smplayer/releases/tag/v10388

It's ok now.

**Comment by SafeReader** [comment]
It is happening even in the latest version SMPlayer 25.6.0 (revision 10369)
Also, I never use pre-realize or beta versions. I use only final stable versions.
I uninstalled again 25,6 and I installed the version 24.5 which works fine as you ucan see.

![Image](https://github.com/user-attachments/assets/eda587e4-daa1-4dd8-9877-b96a5067a83c)

**Comment by smplayer-dev** [comment]
I think it's fixed in the development version:
https://github.com/smplayer-dev/smplayer/releases/tag/v10388

**Comment by tdquangvinh-netizen** [comment]
> I think it's fixed in the development version: https://github.com/smplayer-dev/smplayer/releases/tag/v10388
hi, still not fix but, change "mutimedia engine' to mplayer, will fix this issue. I seek for many day and think about the engine later

**Comment by SafeReader** [comment]
I did already the change from mpv to mplayer but then comes other problem.
When the engine is mplayer and temporarily pause the video and I hit any arrow key to move a few seconds later or earlier the movie starts playing again instead of going just later or earlier and staying there.
So I'll wait for the next STABLE final version, not any BETA, to see if will be fixed. Till then I stay to version 24.5

**Comment by sahfd4eiugf** [comment]
I have the same exact issue and it's driving me NUTS.

Is the video rotation also bugged when you enable "Remember Media Settings" ?

In the previous SMplayer version the rotation was correctly applied after re-opening a closed video. Now not only it is distorted, but its not even applied anymore .

**Comment by sahfd4eiugf** [comment]
> I think it's fixed in the development version: https://github.com/smplayer-dev/smplayer/releases/tag/v10388

Still heavily distorted in 10388

<img width="1255" height="1121" alt="Image" src="https://github.com/user-attachments/assets/524c1b20-e7cb-43c3-b18e-196ab20b442f" />

**Comment by smplayer-dev** [comment]
I can't reproduce this problem in my computer using version 10388.

**Comment by mbilykov** [comment]
Hi there,

I did have same issue with revision 10369. After i did install revision 10388 issue is gone.
