### ISSUE TITLE
smplayer passes wrong --audio-channels to mpv

### ISSUE THREAD

**Issue by corvus1** [smplayer-dev/smplayer#176]
Smplayer passes `--audio-channels=6` to mpv, which according to `mpv --audio-channels=help` is not a correct channel layout. And it is outputting stereo, instead of 5.1. As a workaround I passed `--audio-channels=auto-safe` as an extra parameter, which worked. 

 - SMPlayer version: 21.1.0 rev 9843 built from git
 - OS: gentoo linux
 [ ] MPlayer
 [x] MPV

**Comment by smplayer-dev** [comment]
I think it's fixed in version [9872](https://github.com/smplayer-dev/smplayer/releases/tag/v21.1.0.9872). Could you test it?

**Comment by corvus1** [comment]
It certainly changed the behavior, and now it passes --audio-channels=5.1. However, for whatever reason, I'm still getting 2-channel stereo output, unless I pass additional --audio-channels=auto-safe. Even if in settings > general > audio I set default channels to "default", it still passes 5.1
So, there might be a different problem on top of the other problem, and it might be with my audio setup or mpv. However, I kinda expected smplayer to pass --audio-channels=auto-safe or not pass anything at all, if I set audio channels to default in smplayer settings.

**Comment by corvus1** [comment]
C++ is not my forte, but I'm looking at the code, where it's handling that setting, and I see it looking for option 2, 4, 6, 7, and 8, but it does nothing for option 1 (default). Which kinda makes me think there should be no parameter passed to mpv in that case. But it still passes 5.1, for whatever reason.

**Comment by corvus1** [comment]
I think I see what's going on.
https://github.com/smplayer-dev/smplayer/blob/154349ba055647bf0a2cd854a32793546eb59d4e/src/mediasettings.cpp#L595-L596

I'm guessing if that setting is set to default, it's setting it to 5.1 somehow automagically. Which would work probably in many situations, but it doesn't work for me.

**Comment by smplayer-dev** [comment]
According to the [mpv manual](https://mpv.io/manual/stable/#options-audio-channels) the `auto-safe` option is the default, so I don't know why you need to explicitly pass it.

The option in settings -> general -> audio is only used for files never played before.

**Comment by corvus1** [comment]
I need to pass `auto-safe` because smplayer passes `--audio-channels=5.1` which results in 2-channel audio on my system. So I'm basically negating what smplayer does, and reverting mpv to default behavior. Is there a way for me to ask smplayer to simply stop passing that argument?

**Comment by corvus1** [comment]
> The option in settings -> general -> audio is only used for files never played before.

Indeed! I just tried with a new file never played before, and smplayer doesn't pass 5.1 and the audio is in all 6 speakers!

**Comment by corvus1** [comment]
So basically I could delete `~/.config/smplayer/file_settings` and then remove the extra `auto-safe` option. I'm guessing, we can close the bug at this point, because the remaining problem seems to be specific to my setup. It is a strange behavior, however. You can basically play with the option in settings -> general -> audio, then revert it to what it was, but it will store it on a file-specific basis. So basically, the user can revert the option to default, but the behavior of the program with that file is now changed.

**Comment by smplayer-dev** [comment]
> I need to pass `auto-safe` because smplayer passes `--audio-channels=5.1` which results in 2-channel audio on my system. So I'm basically negating what smplayer does, and reverting mpv to default behavior. Is there a way for me to ask smplayer to simply stop passing that argument?

Audio -> Channels -> Default.

**Comment by corvus1** [comment]
> Audio -> Channels -> Default.

<s>well, yeah, I did that, but like you said it only works for files never played before</s>

Scratch that. I found the option in the menu, thanks!
