### ISSUE TITLE
play/pause at some point stumbles and no longer reacts

### ISSUE THREAD

**Issue by kmikita** [smplayer-dev/smplayer#904]
**Describe the bug**
Play/pause at some point stumbles and no longer reacts. Afler workaround #837 bag affects mpv 0.36 also.

**To Reproduce**
Press play/pause frequently or hold on.

**Comment by AngryPhantom** [comment]
I can confirm this. Any fix or test version please?  
smplayer 23.12.0  
mpv 0.37.0  
Arch Linux

**Comment by Raza-0007** [comment]
I am using smplayer 23.12.0, mpv build 0.37.0-262-gfd2c5ee2 (Feb 7th build) on Windows 11.

I cannot replicate this issue on my system. Play/pause work fine no matter how many times I click the space bar or mouse.

~Raza

**Comment by AngryPhantom** [comment]
Today the problem has miraculously gone. Looked in the logs and only gstreamer and its plugins were updated.
Edit: it's unrelevant. The problem is gone. Strange, but I've experienced it randomly yesterday.

**Comment by Raza-0007** [comment]
When smplayer starts acting up I have found that re-setting it to its default settings usually corrects the issues. You can reset smplayer to default by deleting the `smplayer.ini` and `playlist.ini` files in its configuration folder. I do that once every 4-5 months and this helps keep such issues away.

~Raza

**Comment by AngryPhantom** [comment]
@Raza-0007 It's obvious that we've done that. But it didn't help. The problem appeared within the changes in mpv code, in version 0.37.

**Comment by Raza-0007** [comment]
I meant if the issue occurs in an already patched version. smplayer 23.12.0 has this play/pause issue with mpv 0.37 fixed, so if someone were to experience this issue on 23.12.0, provided nothing has changed in mpv since 23.12.0 was released, then re-setting smplayer to default will help.   

~Raza

**Comment by yorii** [comment]
I have tried with mpv version 0.37, 0.36, and 0.35, issue is identical regardless of what mpv build being used.

Downgrading to smplayer 23.6.0 removes the issue completely, and works with all of the aforementioned versions of mpv.

Can be easily reproduced by pressing play/pause in quick succession 3 times.

**Comment by Raza-0007** [comment]
Must be OS specific. I do not have this on Windows 11. I was going to say it might be Linux specific, but the OP on [this thread](https://github.com/smplayer-dev/smplayer/issues/837) uses Linux and his issue was fixed with the patch.

You may need to post logs and wait for @smplayer-dev to investigate, because I do not use Linux.

~Raza

**Comment by smplayer-dev** [comment]
I can't reproduce this problem in my computer.
Anyway, can you check if the snap or flatpak packages of the latest version still have this problem?
https://github.com/smplayer-dev/smplayer/releases/tag/v23.12.0.10229

**Comment by yorii** [comment]
> I can't reproduce this problem in my computer. Anyway, can you check if the snap or flatpak packages of the latest version still have this problem? https://github.com/smplayer-dev/smplayer/releases/tag/v23.12.0.10229

Seems to be 100% fixed and working now in that latest revision 10229! Just using the normal installer. Seeking times in general seem to also be very much improved overall!

**Comment by kmikita** [comment]
Ubuntu 18.04, kernel 6.5.7.
Issue still reproducible.

```
$ smplayer
qt5ct: using qt5ct plugin
SMPlayer v. 23.12.0 (ревизия 10229) запущен в Linux
```

<details>
  <summary>SMPlayer log</summary>

```
[18:59:53:670] PlayerID::Player: player_bin: "/usr/local/bin/mpv" filename: "mpv"
[18:59:53:711] MplayerWindow::mouseReleaseEvent
[18:59:53:711] BaseGui::leftClickFunction
[18:59:54:093] GlobalShortcuts::nativeEventFilter: keycode: 65
[18:59:54:095] Core::pause: current state: "Playing"
[18:59:54:095] MPVProcess::sendCommand: "set pause yes"
[18:59:54:095] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:096] MPVProcess::parseLine: paused
[18:59:54:096] Core::changePause
[18:59:54:096] Core::changePause: mplayer reports that it's paused
[18:59:54:096] BaseGui::displayState: "Paused"
[18:59:54:097] MiniGui::togglePlayAction
[18:59:54:097] BaseGui::togglePlayAction
[18:59:54:097] BaseGui::checkStayOnTop
[18:59:54:594] Core::pause: current state: "Paused"
[18:59:54:594] MPVProcess::sendCommand: "set pause no"
[18:59:54:614] MPVProcess::parseLine: idle
[18:59:54:614] BaseGui::displayState: "Unknown"
[18:59:54:614] MiniGui::togglePlayAction
[18:59:54:614] BaseGui::togglePlayAction
[18:59:54:615] BaseGui::checkStayOnTop
[18:59:54:629] Core::pause: current state: "Unknown"
[18:59:54:629] MPVProcess::sendCommand: "set pause yes"
[18:59:54:629] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:662] Core::pause: current state: "Unknown"
[18:59:54:662] MPVProcess::sendCommand: "set pause yes"
[18:59:54:662] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:696] Core::pause: current state: "Unknown"
[18:59:54:696] MPVProcess::sendCommand: "set pause yes"
[18:59:54:696] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:730] Core::pause: current state: "Unknown"
[18:59:54:730] MPVProcess::sendCommand: "set pause yes"
[18:59:54:730] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:763] Core::pause: current state: "Unknown"
[18:59:54:763] MPVProcess::sendCommand: "set pause yes"
[18:59:54:763] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:796] Core::pause: current state: "Unknown"
[18:59:54:796] MPVProcess::sendCommand: "set pause yes"
[18:59:54:796] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:828] Core::pause: current state: "Unknown"
[18:59:54:829] MPVProcess::sendCommand: "set pause yes"
[18:59:54:829] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:862] Core::pause: current state: "Unknown"
[18:59:54:862] MPVProcess::sendCommand: "set pause yes"
[18:59:54:862] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:895] Core::pause: current state: "Unknown"
[18:59:54:895] MPVProcess::sendCommand: "set pause yes"
[18:59:54:895] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:928] Core::pause: current state: "Unknown"
[18:59:54:929] MPVProcess::sendCommand: "set pause yes"
[18:59:54:929] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:962] Core::pause: current state: "Unknown"
[18:59:54:962] MPVProcess::sendCommand: "set pause yes"
[18:59:54:962] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:54:995] Core::pause: current state: "Unknown"
[18:59:54:995] MPVProcess::sendCommand: "set pause yes"
[18:59:54:995] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:028] Core::pause: current state: "Unknown"
[18:59:55:028] MPVProcess::sendCommand: "set pause yes"
[18:59:55:029] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:062] Core::pause: current state: "Unknown"
[18:59:55:062] MPVProcess::sendCommand: "set pause yes"
[18:59:55:062] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:095] Core::pause: current state: "Unknown"
[18:59:55:095] MPVProcess::sendCommand: "set pause yes"
[18:59:55:095] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:128] Core::pause: current state: "Unknown"
[18:59:55:128] MPVProcess::sendCommand: "set pause yes"
[18:59:55:128] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:161] Core::pause: current state: "Unknown"
[18:59:55:161] MPVProcess::sendCommand: "set pause yes"
[18:59:55:161] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:194] Core::pause: current state: "Unknown"
[18:59:55:194] MPVProcess::sendCommand: "set pause yes"
[18:59:55:194] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:227] Core::pause: current state: "Unknown"
[18:59:55:227] MPVProcess::sendCommand: "set pause yes"
[18:59:55:227] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:260] Core::pause: current state: "Unknown"
[18:59:55:260] MPVProcess::sendCommand: "set pause yes"
[18:59:55:260] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:293] Core::pause: current state: "Unknown"
[18:59:55:293] MPVProcess::sendCommand: "set pause yes"
[18:59:55:293] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:326] Core::pause: current state: "Unknown"
[18:59:55:326] MPVProcess::sendCommand: "set pause yes"
[18:59:55:326] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:359] Core::pause: current state: "Unknown"
[18:59:55:359] MPVProcess::sendCommand: "set pause yes"
[18:59:55:359] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:392] Core::pause: current state: "Unknown"
[18:59:55:392] MPVProcess::sendCommand: "set pause yes"
[18:59:55:392] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:425] Core::pause: current state: "Unknown"
[18:59:55:425] MPVProcess::sendCommand: "set pause yes"
[18:59:55:425] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:458] Core::pause: current state: "Unknown"
[18:59:55:458] MPVProcess::sendCommand: "set pause yes"
[18:59:55:458] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:491] Core::pause: current state: "Unknown"
[18:59:55:491] MPVProcess::sendCommand: "set pause yes"
[18:59:55:491] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:524] Core::pause: current state: "Unknown"
[18:59:55:524] MPVProcess::sendCommand: "set pause yes"
[18:59:55:524] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:557] Core::pause: current state: "Unknown"
[18:59:55:557] MPVProcess::sendCommand: "set pause yes"
[18:59:55:558] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:591] Core::pause: current state: "Unknown"
[18:59:55:591] MPVProcess::sendCommand: "set pause yes"
[18:59:55:591] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:623] Core::pause: current state: "Unknown"
[18:59:55:624] MPVProcess::sendCommand: "set pause yes"
[18:59:55:624] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:657] Core::pause: current state: "Unknown"
[18:59:55:657] MPVProcess::sendCommand: "set pause yes"
[18:59:55:657] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:690] Core::pause: current state: "Unknown"
[18:59:55:690] MPVProcess::sendCommand: "set pause yes"
[18:59:55:690] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:723] Core::pause: current state: "Unknown"
[18:59:55:724] MPVProcess::sendCommand: "set pause yes"
[18:59:55:724] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:756] Core::pause: current state: "Unknown"
[18:59:55:756] MPVProcess::sendCommand: "set pause yes"
[18:59:55:756] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:55:908] GlobalShortcuts::nativeEventFilter: keycode: 65
[18:59:55:908] Core::pause: current state: "Unknown"
[18:59:55:908] MPVProcess::sendCommand: "set pause yes"
[18:59:55:908] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[18:59:58:014] BaseGui::showMplayerLog
[19:00:03:513] BaseGui::showLog
[19:00:10:364] MplayerWindow::mouseReleaseEvent
[19:00:10:365] BaseGui::leftClickFunction
[19:00:11:352] GlobalShortcuts::nativeEventFilter: keycode: 65
[19:00:11:358] Core::pause: current state: "Unknown"
[19:00:11:365] MPVProcess::sendCommand: "set pause yes"
[19:00:11:368] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:11:853] Core::pause: current state: "Unknown"
[19:00:11:853] MPVProcess::sendCommand: "set pause yes"
[19:00:11:854] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:11:886] Core::pause: current state: "Unknown"
[19:00:11:887] MPVProcess::sendCommand: "set pause yes"
[19:00:11:888] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:11:919] Core::pause: current state: "Unknown"
[19:00:11:921] MPVProcess::sendCommand: "set pause yes"
[19:00:11:921] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:11:953] Core::pause: current state: "Unknown"
[19:00:11:954] MPVProcess::sendCommand: "set pause yes"
[19:00:11:954] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:11:986] Core::pause: current state: "Unknown"
[19:00:11:987] MPVProcess::sendCommand: "set pause yes"
[19:00:11:988] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:019] Core::pause: current state: "Unknown"
[19:00:12:020] MPVProcess::sendCommand: "set pause yes"
[19:00:12:021] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:053] Core::pause: current state: "Unknown"
[19:00:12:054] MPVProcess::sendCommand: "set pause yes"
[19:00:12:054] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:086] Core::pause: current state: "Unknown"
[19:00:12:087] MPVProcess::sendCommand: "set pause yes"
[19:00:12:088] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:119] Core::pause: current state: "Unknown"
[19:00:12:120] MPVProcess::sendCommand: "set pause yes"
[19:00:12:121] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:153] Core::pause: current state: "Unknown"
[19:00:12:154] MPVProcess::sendCommand: "set pause yes"
[19:00:12:155] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:186] Core::pause: current state: "Unknown"
[19:00:12:187] MPVProcess::sendCommand: "set pause yes"
[19:00:12:188] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:219] Core::pause: current state: "Unknown"
[19:00:12:220] MPVProcess::sendCommand: "set pause yes"
[19:00:12:221] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:252] Core::pause: current state: "Unknown"
[19:00:12:253] MPVProcess::sendCommand: "set pause yes"
[19:00:12:254] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:285] Core::pause: current state: "Unknown"
[19:00:12:286] MPVProcess::sendCommand: "set pause yes"
[19:00:12:286] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:318] Core::pause: current state: "Unknown"
[19:00:12:319] MPVProcess::sendCommand: "set pause yes"
[19:00:12:320] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:352] Core::pause: current state: "Unknown"
[19:00:12:353] MPVProcess::sendCommand: "set pause yes"
[19:00:12:353] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:385] Core::pause: current state: "Unknown"
[19:00:12:386] MPVProcess::sendCommand: "set pause yes"
[19:00:12:387] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:418] Core::pause: current state: "Unknown"
[19:00:12:419] MPVProcess::sendCommand: "set pause yes"
[19:00:12:420] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:452] Core::pause: current state: "Unknown"
[19:00:12:453] MPVProcess::sendCommand: "set pause yes"
[19:00:12:453] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:485] Core::pause: current state: "Unknown"
[19:00:12:486] MPVProcess::sendCommand: "set pause yes"
[19:00:12:487] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:518] Core::pause: current state: "Unknown"
[19:00:12:519] MPVProcess::sendCommand: "set pause yes"
[19:00:12:520] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:12:790] GlobalShortcuts::nativeEventFilter: keycode: 65
[19:00:12:792] Core::pause: current state: "Unknown"
[19:00:12:794] MPVProcess::sendCommand: "set pause yes"
[19:00:12:795] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:13:290] Core::pause: current state: "Unknown"
[19:00:13:291] MPVProcess::sendCommand: "set pause yes"
[19:00:13:292] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:13:324] Core::pause: current state: "Unknown"
[19:00:13:325] MPVProcess::sendCommand: "set pause yes"
[19:00:13:326] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:13:358] Core::pause: current state: "Unknown"
[19:00:13:359] MPVProcess::sendCommand: "set pause yes"
[19:00:13:360] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:13:391] Core::pause: current state: "Unknown"
[19:00:13:392] MPVProcess::sendCommand: "set pause yes"
[19:00:13:393] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:13:424] Core::pause: current state: "Unknown"
[19:00:13:425] MPVProcess::sendCommand: "set pause yes"
[19:00:13:426] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:13:458] Core::pause: current state: "Unknown"
[19:00:13:459] MPVProcess::sendCommand: "set pause yes"
[19:00:13:459] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:13:491] Core::pause: current state: "Unknown"
[19:00:13:492] MPVProcess::sendCommand: "set pause yes"
[19:00:13:493] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:13:524] Core::pause: current state: "Unknown"
[19:00:13:525] MPVProcess::sendCommand: "set pause yes"
[19:00:13:526] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:14:034] GlobalShortcuts::nativeEventFilter: keycode: 65
[19:00:14:036] Core::pause: current state: "Unknown"
[19:00:14:038] MPVProcess::sendCommand: "set pause yes"
[19:00:14:039] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:14:646] GlobalShortcuts::nativeEventFilter: keycode: 65
[19:00:14:649] Core::pause: current state: "Unknown"
[19:00:14:651] MPVProcess::sendCommand: "set pause yes"
[19:00:14:652] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:15:006] GlobalShortcuts::nativeEventFilter: keycode: 65
[19:00:15:009] Core::pause: current state: "Unknown"
[19:00:15:010] MPVProcess::sendCommand: "set pause yes"
[19:00:15:011] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:15:329] GlobalShortcuts::nativeEventFilter: keycode: 65
[19:00:15:333] Core::pause: current state: "Unknown"
[19:00:15:334] MPVProcess::sendCommand: "set pause yes"
[19:00:15:335] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:15:582] GlobalShortcuts::nativeEventFilter: keycode: 65
[19:00:15:585] Core::pause: current state: "Unknown"
[19:00:15:586] MPVProcess::sendCommand: "set pause yes"
[19:00:15:587] MPVProcess::sendCommand: "no-osd seek 0 relative exact"
[19:00:16:283] GlobalShortcuts::nativeEventFilter: keycode: 65
[19:00:16:288] Core::pause: current state: "Unknown"
[19:00:16:289] MPVProcess::sendCommand: "set pause yes"
[19:00:16:290] MPVProcess::sendCommand: "no-osd seek 0 relative exact"

```

</details>

```
$ /usr/local/bin/mpv -V
mpv 0.36.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Wed Nov 29 09:29:01 2023
libplacebo version: v6.338.0-1-gd3225154
FFmpeg version: 6.1-dx
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

<details>
  <summary>ldd /usr/local/bin/mpv</summary>

```
$ ldd /usr/local/bin/mpv
	linux-vdso.so.1 (0x00007ffe743ac000)
	libass.so.9 => /usr/lib/x86_64-linux-gnu/libass.so.9 (0x00007f03a7a00000)
	libavcodec.so.60 => /usr/local/lib/libavcodec.so.60 (0x00007f03a6400000)
	libavfilter.so.9 => /usr/local/lib/libavfilter.so.9 (0x00007f03a5c00000)
	libavformat.so.60 => /usr/local/lib/libavformat.so.60 (0x00007f03a5600000)
	libavutil.so.58 => /usr/local/lib/libavutil.so.58 (0x00007f03a4200000)
	libswresample.so.4 => /usr/local/lib/libswresample.so.4 (0x00007f03a3e00000)
	libswscale.so.7 => /usr/local/lib/libswscale.so.7 (0x00007f03a3a00000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f03a3600000)
	libdvdnav.so.4 => /usr/local/lib/libdvdnav.so.4 (0x00007f03a3200000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f03a2e00000)
	libarchive.so.13 => /usr/lib/x86_64-linux-gnu/libarchive.so.13 (0x00007f03a2a00000)
	libavdevice.so.60 => /usr/local/lib/libavdevice.so.60 (0x00007f03a2600000)
	libbluray.so.2 => /usr/lib/x86_64-linux-gnu/libbluray.so.2 (0x00007f03a2200000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f03a1e00000)
	libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007f03a1a00000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f03a1600000)
	libluajit-5.1.so.2 => /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2 (0x00007f03a1200000)
	librubberband.so.2 => /usr/lib/x86_64-linux-gnu/librubberband.so.2 (0x00007f03a0e00000)
	libuchardet.so.0 => /usr/lib/x86_64-linux-gnu/libuchardet.so.0 (0x00007f03a0a00000)
	libvapoursynth-script.so.0 => /usr/local/lib/libvapoursynth-script.so.0 (0x00007f03a0600000)
	libzimg.so.2 => /usr/local/lib/libzimg.so.2 (0x00007f03a0200000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f039fe00000)
	libasound.so.2 => /usr/local/lib/libasound.so.2 (0x00007f039fa00000)
	libjack.so.0 => /usr/lib/x86_64-linux-gnu/libjack.so.0 (0x00007f039f600000)
	libpulse.so.0 => /usr/local/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f039f200000)
	libcaca.so.0 => /usr/lib/x86_64-linux-gnu/libcaca.so.0 (0x00007f039ee00000)
	libdrm.so.2 => /opt/xorg/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f039ea00000)
	libgbm.so.1 => /opt/xorg/lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f039e600000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f039e200000)
	libplacebo.so.338 => /usr/local/lib/x86_64-linux-gnu/libplacebo.so.338 (0x00007f039de00000)
	libwayland-client.so.0 => /usr/local/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f039da00000)
	libwayland-cursor.so.0 => /usr/local/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f039d600000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f039d200000)
	libX11.so.6 => /opt/xorg/lib/libX11.so.6 (0x00007f039ce00000)
	libXss.so.1 => /opt/xorg/lib/libXss.so.1 (0x00007f039ca00000)
	libXext.so.6 => /opt/xorg/lib/libXext.so.6 (0x00007f039c600000)
	libXinerama.so.1 => /opt/xorg/lib/libXinerama.so.1 (0x00007f039c200000)
	libXpresent.so.1 => /usr/lib/x86_64-linux-gnu/libXpresent.so.1 (0x00007f039be00000)
	libXrandr.so.2 => /opt/xorg/lib/libXrandr.so.2 (0x00007f039ba00000)
	libXv.so.1 => /opt/xorg/lib/libXv.so.1 (0x00007f039b600000)
	libGL.so.1 => /opt/xorg/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f039b200000)
	libEGL.so.1 => /opt/xorg/lib/x86_64-linux-gnu/libEGL.so.1 (0x00007f039ae00000)
	libwayland-egl.so.1 => /usr/local/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f039aa00000)
	libva.so.2 => /usr/local/lib/libva.so.2 (0x00007f039a600000)
	libva-drm.so.2 => /usr/local/lib/libva-drm.so.2 (0x00007f039a200000)
	libva-wayland.so.2 => /usr/lib/x86_64-linux-gnu/libva-wayland.so.2 (0x00007f0399e00000)
	libva-x11.so.2 => /usr/local/lib/libva-x11.so.2 (0x00007f0399a00000)
	libvdpau.so.1 => /usr/lib/x86_64-linux-gnu/libvdpau.so.1 (0x00007f0399600000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0399200000)
	libfribidi.so.0 => /usr/local/lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f0398e00000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f0398a00000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f0398600000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f0398200000)
	libvpx.so.5 => /usr/lib/x86_64-linux-gnu/libvpx.so.5 (0x00007f0397c00000)
	libwebpmux.so.3 => /usr/lib/x86_64-linux-gnu/libwebpmux.so.3 (0x00007f0397800000)
	libwebp.so.6 => /usr/lib/x86_64-linux-gnu/libwebp.so.6 (0x00007f0397400000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f0397000000)
	librsvg-2.so.2 => /usr/lib/x86_64-linux-gnu/librsvg-2.so.2 (0x00007f0396c00000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f0396800000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f0396400000)
	libcairo.so.2 => /usr/lib/x86_64-linux-gnu/libcairo.so.2 (0x00007f0396000000)
	libzvbi.so.0 => /usr/lib/x86_64-linux-gnu/libzvbi.so.0 (0x00007f0395c00000)
	libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f0395800000)
	libgsm.so.1 => /usr/lib/x86_64-linux-gnu/libgsm.so.1 (0x00007f0395400000)
	libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f0395000000)
	libopenjp2.so.7 => /usr/lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f0394c00000)
	libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f0394800000)
	libshine.so.3 => /usr/lib/x86_64-linux-gnu/libshine.so.3 (0x00007f0394400000)
	libspeex.so.1 => /usr/lib/x86_64-linux-gnu/libspeex.so.1 (0x00007f0394000000)
	libtheoraenc.so.1 => /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007f0393c00000)
	libtheoradec.so.1 => /usr/lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007f0393800000)
	libtwolame.so.0 => /usr/lib/x86_64-linux-gnu/libtwolame.so.0 (0x00007f0393400000)
	libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f0393000000)
	libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f0392c00000)
	libx264.so.164 => /usr/local/lib/libx264.so.164 (0x00007f0392600000)
	libx265.so.207 => /usr/local/lib/libx265.so.207 (0x00007f0391e00000)
	libxvidcore.so.4 => /usr/local/lib/libxvidcore.so.4 (0x00007f0391a00000)
	libpostproc.so.57 => /usr/local/lib/libpostproc.so.57 (0x00007f0391600000)
	libbs2b.so.0 => /usr/lib/x86_64-linux-gnu/libbs2b.so.0 (0x00007f0391200000)
	libflite_cmu_us_awb.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_awb.so.1 (0x00007f0390c00000)
	libflite_cmu_us_kal.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal.so.1 (0x00007f0390800000)
	libflite_cmu_us_kal16.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal16.so.1 (0x00007f0390200000)
	libflite_cmu_us_rms.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_rms.so.1 (0x00007f038fa00000)
	libflite_cmu_us_slt.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmu_us_slt.so.1 (0x00007f038f400000)
	libflite.so.1 => /usr/lib/x86_64-linux-gnu/libflite.so.1 (0x00007f038f000000)
	libvidstab.so.1.2 => /usr/local/lib/libvidstab.so.1.2 (0x00007f038ec00000)
	libzmq.so.5 => /usr/lib/x86_64-linux-gnu/libzmq.so.5 (0x00007f038e800000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f038e400000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f038e000000)
	libgme.so.0 => /usr/lib/x86_64-linux-gnu/libgme.so.0 (0x00007f038dc00000)
	libopenmpt.so.0 => /usr/lib/x86_64-linux-gnu/libopenmpt.so.0 (0x00007f038d800000)
	libchromaprint.so.1 => /usr/local/lib/libchromaprint.so.1 (0x00007f038d400000)
	libgnutls.so.30 => /usr/local/lib/libgnutls.so.30 (0x00007f038d000000)
	libssh.so.4 => /usr/lib/x86_64-linux-gnu/libssh.so.4 (0x00007f038cc00000)
	libsoxr.so.0 => /usr/local/lib/libsoxr.so.0 (0x00007f038c800000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f03a8400000)
	libdvdread.so.8 => /usr/local/lib/libdvdread.so.8 (0x00007f038c400000)
	libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f038c000000)
	libacl.so.1 => /lib/x86_64-linux-gnu/libacl.so.1 (0x00007f038bc00000)
	libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f038b800000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f038b400000)
	libraw1394.so.11 => /usr/lib/x86_64-linux-gnu/libraw1394.so.11 (0x00007f038b000000)
	libavc1394.so.0 => /usr/lib/x86_64-linux-gnu/libavc1394.so.0 (0x00007f038ac00000)
	librom1394.so.0 => /usr/lib/x86_64-linux-gnu/librom1394.so.0 (0x00007f038a800000)
	libiec61883.so.0 => /usr/lib/x86_64-linux-gnu/libiec61883.so.0 (0x00007f038a400000)
	libopenal.so.1 => /usr/lib/x86_64-linux-gnu/libopenal.so.1 (0x00007f038a000000)
	libxcb.so.1 => /opt/xorg/lib/libxcb.so.1 (0x00007f0389c00000)
	libxcb-shm.so.0 => /opt/xorg/lib/libxcb-shm.so.0 (0x00007f0389800000)
	libxcb-shape.so.0 => /opt/xorg/lib/libxcb-shape.so.0 (0x00007f0389400000)
	libxcb-xfixes.so.0 => /opt/xorg/lib/libxcb-xfixes.so.0 (0x00007f0389000000)
	libdc1394.so.22 => /usr/lib/x86_64-linux-gnu/libdc1394.so.22 (0x00007f0388c00000)
	libSDL2-2.0.so.0 => /usr/local/lib/libSDL2-2.0.so.0 (0x00007f0388800000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0388400000)
	libsamplerate.so.0 => /usr/local/lib/libsamplerate.so.0 (0x00007f0388000000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007f0387a00000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0387400000)
	libpython3.8.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 (0x00007f0386c00000)
	libdb-5.3.so => /usr/lib/x86_64-linux-gnu/libdb-5.3.so (0x00007f0386800000)
	libpulsecommon-16.1.so => /usr/local/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-16.1.so (0x00007f0386400000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f0386000000)
	libslang.so.2 => /lib/x86_64-linux-gnu/libslang.so.2 (0x00007f0385a00000)
	libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007f0385600000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f0385200000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f0384e00000)
	libunwind.so.8 => /usr/lib/x86_64-linux-gnu/libunwind.so.8 (0x00007f0384a00000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f0384600000)
	libXrender.so.1 => /opt/xorg/lib/libXrender.so.1 (0x00007f0384200000)
	libglapi.so.0 => /opt/xorg/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f0383e00000)
	libxcb-glx.so.0 => /opt/xorg/lib/libxcb-glx.so.0 (0x00007f0383a00000)
	libX11-xcb.so.1 => /opt/xorg/lib/libX11-xcb.so.1 (0x00007f0383600000)
	libxcb-dri2.so.0 => /opt/xorg/lib/libxcb-dri2.so.0 (0x00007f0383200000)
	libXfixes.so.3 => /opt/xorg/lib/libXfixes.so.3 (0x00007f0382e00000)
	libXxf86vm.so.1 => /opt/xorg/lib/libXxf86vm.so.1 (0x00007f0382a00000)
	libxshmfence.so.1 => /opt/xorg/lib/libxshmfence.so.1 (0x00007f0382600000)
	libxcb-dri3.so.0 => /opt/xorg/lib/libxcb-dri3.so.0 (0x00007f0382200000)
	libxcb-present.so.0 => /opt/xorg/lib/libxcb-present.so.0 (0x00007f0381e00000)
	libxcb-sync.so.1 => /opt/xorg/lib/libxcb-sync.so.1 (0x00007f0381a00000)
	libxcb-randr.so.0 => /opt/xorg/lib/libxcb-randr.so.0 (0x00007f0381600000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f0381200000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f0380e00000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0 (0x00007f0380a00000)
	libgio-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0 (0x00007f0380600000)
	libpangocairo-1.0.so.0 => /usr/local/lib/libpangocairo-1.0.so.0 (0x00007f0380200000)
	libpangoft2-1.0.so.0 => /usr/local/lib/libpangoft2-1.0.so.0 (0x00007f037fe00000)
	libpango-1.0.so.0 => /usr/local/lib/libpango-1.0.so.0 (0x00007f037fa00000)
	libcroco-0.6.so.3 => /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3 (0x00007f037f600000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f037f200000)
	libpixman-1.so.0 => /opt/xorg/lib/libpixman-1.so.0 (0x00007f037ee00000)
	libxcb-render.so.0 => /opt/xorg/lib/libxcb-render.so.0 (0x00007f037ea00000)
	libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f037e600000)
	libflite_usenglish.so.1 => /usr/lib/x86_64-linux-gnu/libflite_usenglish.so.1 (0x00007f037e200000)
	libflite_cmulex.so.1 => /usr/lib/x86_64-linux-gnu/libflite_cmulex.so.1 (0x00007f037de00000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f037da00000)
	libsodium.so.23 => /usr/lib/x86_64-linux-gnu/libsodium.so.23 (0x00007f037d600000)
	libpgm-5.2.so.0 => /usr/lib/x86_64-linux-gnu/libpgm-5.2.so.0 (0x00007f037d200000)
	libnorm.so.1 => /usr/lib/x86_64-linux-gnu/libnorm.so.1 (0x00007f037ce00000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f037ca00000)
	libmpg123.so.0 => /usr/lib/x86_64-linux-gnu/libmpg123.so.0 (0x00007f037c600000)
	libvorbisfile.so.3 => /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007f037c200000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f037be00000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f037ba00000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f037b600000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f037b200000)
	libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f037ae00000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f037aa00000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f037a400000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f037a000000)
	libdvdcss.so.2 => /usr/local/lib/libdvdcss.so.2 (0x00007f0379c00000)
	libattr.so.1 => /lib/x86_64-linux-gnu/libattr.so.1 (0x00007f0379800000)
	libsndio.so.6.1 => /usr/lib/x86_64-linux-gnu/libsndio.so.6.1 (0x00007f0379400000)
	libXau.so.6 => /opt/xorg/lib/libXau.so.6 (0x00007f0379000000)
	libXdmcp.so.6 => /opt/xorg/lib/libXdmcp.so.6 (0x00007f0378c00000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f0378800000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f0378400000)
	libsndfile.so.1 => /usr/local/lib/libsndfile.so.1 (0x00007f0378000000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f0377c00000)
	libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f0377800000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f0377400000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f0377000000)
	libmount.so.1 => /lib/x86_64-linux-gnu/libmount.so.1 (0x00007f0376c00000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f0375000000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f0374c00000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f0374800000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f0374400000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f0374000000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f0373c00000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f0373800000)
	libFLAC.so.12 => /usr/local/lib/libFLAC.so.12 (0x00007f0373400000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f0373000000)
	libblkid.so.1 => /usr/local/lib/libblkid.so.1 (0x00007f0372c00000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f0372800000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f0372400000)
```
</details>
<details>
  <summary>ldd $(which smplayer)</summary>

```
$ ldd $(which smplayer)
	linux-vdso.so.1 (0x00007ffc91fc8000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa840c00000)
	libX11.so.6 => /opt/xorg/lib/libX11.so.6 (0x00007fa840800000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007fa83fe00000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fa83f600000)
	libQt5Qml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (0x00007fa83f000000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fa83ec00000)
	libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007fa83e800000)
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007fa83e400000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fa83dc00000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa83d800000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa83d200000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa83ce00000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa83ca00000)
	libxcb.so.1 => /opt/xorg/lib/libxcb.so.1 (0x00007fa83c600000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa83c200000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa83be00000)
	libGL.so.1 => /opt/xorg/lib/x86_64-linux-gnu/libGL.so.1 (0x00007fa83ba00000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fa83b600000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fa83b200000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fa83ae00000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007fa83a800000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007fa83a400000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007fa83a000000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fa839c00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa841800000)
	libXau.so.6 => /opt/xorg/lib/libXau.so.6 (0x00007fa839800000)
	libXdmcp.so.6 => /opt/xorg/lib/libXdmcp.so.6 (0x00007fa839400000)
	libglapi.so.0 => /opt/xorg/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fa839000000)
	libdrm.so.2 => /opt/xorg/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fa838c00000)
	libxcb-glx.so.0 => /opt/xorg/lib/libxcb-glx.so.0 (0x00007fa838800000)
	libX11-xcb.so.1 => /opt/xorg/lib/libX11-xcb.so.1 (0x00007fa838400000)
	libxcb-dri2.so.0 => /opt/xorg/lib/libxcb-dri2.so.0 (0x00007fa838000000)
	libXext.so.6 => /opt/xorg/lib/libXext.so.6 (0x00007fa837c00000)
	libXfixes.so.3 => /opt/xorg/lib/libXfixes.so.3 (0x00007fa837800000)
	libXxf86vm.so.1 => /opt/xorg/lib/libXxf86vm.so.1 (0x00007fa837400000)
	libxcb-shm.so.0 => /opt/xorg/lib/libxcb-shm.so.0 (0x00007fa837000000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fa836c00000)
	libxshmfence.so.1 => /opt/xorg/lib/libxshmfence.so.1 (0x00007fa836800000)
	libxcb-dri3.so.0 => /opt/xorg/lib/libxcb-dri3.so.0 (0x00007fa836400000)
	libxcb-present.so.0 => /opt/xorg/lib/libxcb-present.so.0 (0x00007fa836000000)
	libxcb-sync.so.1 => /opt/xorg/lib/libxcb-sync.so.1 (0x00007fa835c00000)
	libxcb-xfixes.so.0 => /opt/xorg/lib/libxcb-xfixes.so.0 (0x00007fa835800000)
	libxcb-randr.so.0 => /opt/xorg/lib/libxcb-randr.so.0 (0x00007fa835400000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fa835000000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fa834c00000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fa834800000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007fa832c00000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fa832800000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa832400000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fa832000000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fa831c00000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fa831800000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fa831400000)
```
</details>

**Comment by tbertels** [comment]
Still reproducible on Manjaro, kernel 6.6.19, mpv 0.37.0, smplayer 23.12.0 (revision 10229).

But I've just noticed that if I enable the verbose mpv log in smplayer advanced preferences, it's not reproducible anymore.

**Comment by smplayer-dev** [comment]
Sounds like a side effect of the workaround for bug #837.
The flatpak and snap packages from the development version doesn't include that workaround, so try them.
https://github.com/smplayer-dev/smplayer/releases/tag/v23.12.0.10229

The regular packages (deb, rpm) does have the workaround.

**Comment by smplayer-dev** [comment]
The following version uses a different workaround which shouldn't have any side effects.
Could you test it?
https://github.com/smplayer-dev/smplayer/releases/tag/v23.12.0.10237

**Comment by tbertels** [comment]
Indeed, it works fine with 10237.

The first time I opened the about window, it froze for a few seconds, and it took again a few second to close SMPlayer, but hopefully it's not related and I couldn't reproduce it.

**Comment by Raza-0007** [comment]
@smplayer-dev,

Ricardo, with this new workaround the play/pause issue has reappeared in the Windows version with mpv 0.37!

Is there a way to apply this new workaround only for Linux based distributions, and leave the old workaround that you implemented in the December 26 release version, 23.12.0 (revision 10207), for Windows based smplayer?

That workaround has been working flawlessly in the Windows based smplayer with mpv 0.37 

Here are the bottom portions of the logs on Windows 11, using the new smplayer 23.12.0 (revision 10237) and mpv v0.37.0-262-gfd2c5ee2. The issue occurs at the very end.

[mpv log.txt](https://github.com/smplayer-dev/smplayer/files/14593839/mpv.log.txt)
[smplayer log.txt](https://github.com/smplayer-dev/smplayer/files/14593840/smplayer.log.txt)


~Raza

p.s. Another option may be to just upgrade the mpv inside smplayer to the latest v0.37. mpv 0.37 is now 4 months old and very stable. This will get rid of this mpv 0.36 vs 0.37 issues that keep on cropping up. If you do decide to upgrade to mpv 0.37, please use one of the latest releases, the mpv 0.37 release build version from November 2023 had some issues with smooth playback.

**Comment by smplayer-dev** [comment]
> @smplayer-dev,
> 
> Ricardo, with this new workaround the play/pause issue has reappeared in the Windows version with mpv 0.37!

I can't reproduce the problem in my computer.

**Comment by Raza-0007** [comment]
> I can't reproduce the problem in my computer.

If you hit pause/play multiple times, around 6th or 7th time, you will need to hit play twice to un-pause the video, or you will have to hit pause twice to pause the video. It happens randomly.

You can see it in the bottom portion of the mpv log I uploaded earlier, where I had to hit pause twice to pause the video.

I know this is not a normal way to use pause/play, but the same thing does not happen on the Dec 26 release build. You can spam pause/play as many times as you like and it works each time.

By the way, this is with mpv 0.37. Also, I am not planning to upgrade from the Dec 26 release build any time soon as it is working flawlessly, so there is no rush. I just don't want this new workaround code becoming a part of the new release build :grin:

~Raza

**Comment by smplayer-dev** [comment]
I used a different workaround in build 10241.
Could you test it it works better for you?
https://github.com/smplayer-dev/smplayer/actions/runs/8308005063
(the artifacts at the bottom)

**Comment by tbertels** [comment]
It works fine with build 10241 on Linux.

Note that it actually didn't work correctly with build 10237 on Linux: after a few pause/play, there was the same behavior as reported by [Raza-0007](https://github.com/Raza-0007) for Windows. I didn't notice it because it required 6 or 7 pause/play.

**Comment by Raza-0007** [comment]
@smplayer-dev,

Ricardo, build 10241 is perfect! I spammed the play/pause and it worked each time. 
Thank you.

Just something I noticed in the smplayer log with this build. The following line prints multiple times after each play/pause. It does not effect anything, just makes the log much longer.

`[18:15:06:007] MPVProcess::sendCommand: "print_text IGNORE_THIS"`

~Raza

**Comment by smplayer-dev** [comment]
It should be fixed in commit 91c1ffc

**Comment by tbertels** [comment]
Unfortunately, I actually still have that problem (need to hit play twice to un-pause the video) from time to time with 10241, but much less often.
[mpv.log](https://github.com/smplayer-dev/smplayer/files/14657268/mpv.log)
[smplayer.log](https://github.com/smplayer-dev/smplayer/files/14657269/smplayer.log)

**Comment by smplayer-dev** [comment]
This version includes mpv 0.37, could you test if it works correctly?
https://github.com/smplayer-dev/smplayer/releases/tag/v23.12.0.10242

**Comment by tbertels** [comment]
I already have mpv 0.37 installed, but I tried with the 10242 AppImage anyway, and there's no difference (apart from the cleaner log).
Looking at the log, it seems that SMPlayer can see if the video is still playing:
```
[15:00:39:436] MPVProcess::parseLine: "Set property: pause=yes -> 1"
[15:00:39:959] Core::pause: current state: "Playing"
```
So couldn't SMPlayer resend the same command to mpv in that case?

Fuller log:
```
[15:00:39:326] Core::changeCurrentSec: mplayer reports that now it's playing
[15:00:39:326] BaseGui::checkStayOnTop
[15:00:39:435] Core::pause: current state: "Playing"
[15:00:39:435] MPVProcess::sendCommand: "set pause yes"
[15:00:39:436] MPVProcess::parseLine: "Set property: pause=yes -> 1"
[15:00:39:959] Core::pause: current state: "Playing"
[15:00:39:959] MPVProcess::sendCommand: "set pause yes"
[15:00:39:959] MPVProcess::parseLine: paused
[15:00:39:959] Core::changePause
[15:00:39:959] Core::changePause: mplayer reports that it's paused
[15:00:39:959] BaseGui::displayState: "Paused"
```

**Comment by smplayer-dev** [comment]
Sorry, I forgot to mention that mpv 0.37 is only included in the Windows packages.

**Comment by Raza-0007** [comment]
@tbertels, what is the build date of your mpv 0.37? I no longer have this issue since smplayer 10241. 

Since our smplayers are the same, it could be our mpv players that are different. I initially tested mine on the March 7th build, and now also on the March 19th build of mpv 0.37.

Or it could be some difference between Windows and Linux.

~Raza

**Comment by tbertels** [comment]
@Raza-0007 Thanks for you message!
It was the Jan 19th build.
So I've tried with the latest git (v0.37.0-664-g7490919a9a) but the bug is still there.
I've also tried to open the video directly with mpv, the bug can't be reproduced. Same thing with https://github.com/mpc-qt/mpc-qt

Note that with the latest workaround, the bug only happens when resuming playing the video (have to sometimes press spacebar twice). The bug also seems easier to reproduce when the video is in window mode.
So maybe the same workaround could be applied when resuming playing?

**Comment by smplayer-dev** [comment]
It's just that I can't reproduce the issue. Maybe if I press play/pause 50 times, I might notice something strange once. But it happens so rarely that it's very difficult to know if I've fixed it or not.

**Comment by AngryPhantom** [comment]
Can't reproduce it either anymore. Returned to the repo versions of SMPlayer (23.12.0) and mpv (0.37) on Artix Linux (Arch-based). I honestly don't know why it glitched for me some time ago. I'm still confused. The only explanation is some other system or video package/library... Not sure.

**Comment by Raza-0007** [comment]
> So I've tried with the latest git (v0.37.0-664-g7490919a9a) but the bug is still there.

> Note that with the latest workaround, the bug only happens when resuming playing the video (have to sometimes press spacebar twice). The bug also seems easier to reproduce when the video is in window mode.

@tbertels, then it has to be something going on with your particular system. 

On Windows, this bug was actually resolved somewhere in one of the December builds, the release build of December 26 does not have this issue. The bug was reintroduced in the Windows build 10237, when a new fix was tried for linux, but it was again fixed in build 10241. 

I have just tried it again in build 10241 (March 19th mpv 0.37), both full screen and windowed mode, and I cannot reproduce it, even after clicking play/pause multiple times back to back.

I unfortunately don't have linux, so I cannot test on it, but @smplayer-dev and @AngryPhantom have both tested this on linux and they cannot reproduce it too. I honestly don't know what else to suggest.......

~Raza

**Comment by AngryPhantom** [comment]
I can confirm the double press behavior with any recent mpv version: 0.37, 0.38 and 0.39. Arch Linux.

**Comment by tbertels** [comment]
smplayer uses the terminal for the play/pause functionality, which is against the [mpv recommendations](https://mpv.io/manual/stable/#using-mpv-from-other-programs-or-scripts).

smplayer should fully use the [JSON IPC](https://mpv.io/manual/stable/#json-ipc) socket. It already uses it to send commands, but not to check mpv status.

You can verify this by adding `--terminal=no` to Advanced options, MPlayer/mpv tab, in the "Options" text box.
After doing this, the play/pause functionality will be fully broken.
So right now, if we disable the terminal, the first play/pause command is sent, but then smplayer checks the terminal to see if mpv did play/pause, and it never gets an answer.

**Comment by smplayer-dev** [comment]
I can't reproduce this problem in my computer with mpv 0.38.

**Comment by AngryPhantom** [comment]
Just pause the player, Alt+Tab to Firefox, for example, open some tabs, browse a bit and Alt-Tab back. Poof, the first click on the Space bar doesn't work. Need to press it twice to resume.

**Comment by smplayer-dev** [comment]
I was finally able to reproduce the problem on Ubuntu 24.04.
I think until I could fix it, you can use the snap package, I think it's not affected by the problem.

**Comment by AngryPhantom** [comment]
I guess we'll be fine with a 'double press' for some time. Just take your time. And thanks again for your work!

**Comment by smplayer-dev** [comment]
I think the problem is fixed in master.
However this required to rewrite all the code which reads the communication from mpv, so it might have introduced other bugs.

**Comment by tbertels** [comment]
Nice!
Yes, we can't unpause if we seek while paused.

**Comment by AngryPhantom** [comment]
> we can't unpause if we seek while paused.

Can confirm. Though general pause/unpause looks normal so far (compiled from master).

**Comment by smplayer-dev** [comment]
> Nice! Yes, we can't unpause if we seek while paused.

I think this is fixed now.

**Comment by tbertels** [comment]
Yes, same here. 🙂
And this issue is too.

**Comment by AngryPhantom** [comment]
Looks like it's fixed for me too. Thank you!
